###
POST http://localhost:8000/products/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MCwiQ3JlYXRlZEF0IjoiMjAyNS0xMC0wNFQwMTozODoyOS44MDQwNDMrMDU6MzAiLCJVcGRhdGVkQXQiOiIyMDI1LTEwLTA0VDAxOjM4OjI5LjgwNDA0MyswNTozMCIsIkRlbGV0ZWRBdCI6bnVsbCwiaWQiOjEsIm5hbWUiOiJKb2huIERvZSIsInJvbGUiOjIsImVtYWlsIjoidGVzdDJAZ21haWwuY29tIiwicHJvZmlsZVBpY1VSSSI6IiIsImVtYWlsVmVyaWZpZWQiOmZhbHNlLCJwYXNzd29yZFRyaWVzIjowLCJvcHRlZEluRm9yRW1haWwiOnRydWUsImFjY291bnRTdXNwZW5kZWQiOmZhbHNlLCJhY2NvdW50QmxvY2tlZCI6ZmFsc2UsIm1hcmtlZEZvckRlbGV0aW9uIjpmYWxzZSwiZGVsZXRlQWNjb3VudEFmdGVyIjoiMDAwMS0wMS0wMVQwNTo1MzoyOCswNTo1MyIsImFjY291bnREZWxldGVkIjpmYWxzZSwiYWNjb3VudENyZWF0ZWQiOnRydWUsInRva2VucyI6MCwiZmlsZXMiOm51bGwsImlhdCI6MTc1OTUyMzgwMiwiZXhwIjoxNzYwMTI4NjAyfQ.l0zjuPfsCrwouTvZcvZqMuP2Bw7NE5FrocxSoQ_yaP8
content-type: application/json

{
    "planName": "Basic Plan",
    "planDescription": "This is a basic plan",
    "planPrice": 100,
    "planCurrency": "INR",
    "planDuration": 28,
    "planType": "subscription",
    "tokens": 1000,
    "isActive": true,
    "features": ["Feature1", "Feature2"],
    "paymentGatewayId": {"razorpay": "plan_QX7whUHFlZ1NDR"}
}

###
POST http://localhost:8000/products/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MCwiQ3JlYXRlZEF0IjoiMjAyNS0xMC0wNFQwMTozODoyOS44MDQwNDMrMDU6MzAiLCJVcGRhdGVkQXQiOiIyMDI1LTEwLTA0VDAxOjM4OjI5LjgwNDA0MyswNTozMCIsIkRlbGV0ZWRBdCI6bnVsbCwiaWQiOjEsIm5hbWUiOiJKb2huIERvZSIsInJvbGUiOjIsImVtYWlsIjoidGVzdDJAZ21haWwuY29tIiwicHJvZmlsZVBpY1VSSSI6IiIsImVtYWlsVmVyaWZpZWQiOmZhbHNlLCJwYXNzd29yZFRyaWVzIjowLCJvcHRlZEluRm9yRW1haWwiOnRydWUsImFjY291bnRTdXNwZW5kZWQiOmZhbHNlLCJhY2NvdW50QmxvY2tlZCI6ZmFsc2UsIm1hcmtlZEZvckRlbGV0aW9uIjpmYWxzZSwiZGVsZXRlQWNjb3VudEFmdGVyIjoiMDAwMS0wMS0wMVQwNTo1MzoyOCswNTo1MyIsImFjY291bnREZWxldGVkIjpmYWxzZSwiYWNjb3VudENyZWF0ZWQiOnRydWUsInRva2VucyI6MCwiZmlsZXMiOm51bGwsImlhdCI6MTc1OTUyMzgwMiwiZXhwIjoxNzYwMTI4NjAyfQ.l0zjuPfsCrwouTvZcvZqMuP2Bw7NE5FrocxSoQ_yaP8
content-type: application/json

{
    "planName": "Buy Tokens",
    "planDescription": "This is a one-time purchase plan for tokens",
    "planPrice": 10,
    "planCurrency": "INR",
    "planDuration": 1,
    "planType": "one_time",
    "tokens": 1,
    "isActive": true,
    "features": [],
    "paymentGatewayId": {}
}

###
GET http://localhost:8000/products/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MCwiQ3JlYXRlZEF0IjoiMjAyNS0xMC0wNFQwMTozODoyOS44MDQwNDMrMDU6MzAiLCJVcGRhdGVkQXQiOiIyMDI1LTEwLTA0VDAxOjM4OjI5LjgwNDA0MyswNTozMCIsIkRlbGV0ZWRBdCI6bnVsbCwiaWQiOjEsIm5hbWUiOiJKb2huIERvZSIsInJvbGUiOjIsImVtYWlsIjoidGVzdDJAZ21haWwuY29tIiwicHJvZmlsZVBpY1VSSSI6IiIsImVtYWlsVmVyaWZpZWQiOmZhbHNlLCJwYXNzd29yZFRyaWVzIjowLCJvcHRlZEluRm9yRW1haWwiOnRydWUsImFjY291bnRTdXNwZW5kZWQiOmZhbHNlLCJhY2NvdW50QmxvY2tlZCI6ZmFsc2UsIm1hcmtlZEZvckRlbGV0aW9uIjpmYWxzZSwiZGVsZXRlQWNjb3VudEFmdGVyIjoiMDAwMS0wMS0wMVQwNTo1MzoyOCswNTo1MyIsImFjY291bnREZWxldGVkIjpmYWxzZSwiYWNjb3VudENyZWF0ZWQiOnRydWUsInRva2VucyI6MCwiZmlsZXMiOm51bGwsImlhdCI6MTc1OTUyMzgwMiwiZXhwIjoxNzYwMTI4NjAyfQ.l0zjuPfsCrwouTvZcvZqMuP2Bw7NE5FrocxSoQ_yaP8
