###
POST https://vital-logically-lemming.ngrok-free.app/products/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkpvaG4gRG9lIiwicm9sZSI6MiwiZW1haWwiOiJ0ZXN0MkBnbWFpbC5jb20iLCJwcm9maWxlUGljVVJJIjoiIiwiZW1haWxWZXJpZmllZCI6ZmFsc2UsInBhc3N3b3JkVHJpZXMiOjAsIm9wdGVkSW5Gb3JFbWFpbCI6dHJ1ZSwiYWNjb3VudFN1c3BlbmRlZCI6ZmFsc2UsImFjY291bnRCbG9ja2VkIjpmYWxzZSwibWFya2VkRm9yRGVsZXRpb24iOmZhbHNlLCJkZWxldGVBY2NvdW50QWZ0ZXIiOiIwMDAxLTAxLTAxVDA1OjUzOjI4KzA1OjUzIiwiYWNjb3VudERlbGV0ZWQiOmZhbHNlLCJhY2NvdW50Q3JlYXRlZCI6dHJ1ZSwidG9rZW5zIjowLCJmaWxlcyI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyNS0xMS0wN1QxNTo1NzozMS43ODg4OTErMDU6MzAiLCJ1cGRhdGVkQXQiOiIyMDI1LTExLTA3VDE1OjU3OjMxLjgyODA3MiswNTozMCIsImlhdCI6MTc2MjUxMTI1NiwiZXhwIjoxNzYzMTE2MDU2fQ.J6OBccqec-oq0boxPECAZJhOZivtkH7Xc4uiHlpv-50
content-type: application/json

{
    "planName": "Basic Plan",
    "planDescription": "This is a basic plan",
    "planPrice": 100,
    "planCurrency": "INR",
    "planDuration": 28,
    "planType": "subscription",
    "tokens": 1000,
    "isActive": true,
    "features": ["Feature1", "Feature2"],
    "paymentGatewayId": {"razorpay": "plan_QX7whUHFlZ1NDR"}
}

###
POST https://vital-logically-lemming.ngrok-free.app/products/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkpvaG4gRG9lIiwicm9sZSI6MiwiZW1haWwiOiJ0ZXN0MkBnbWFpbC5jb20iLCJwcm9maWxlUGljVVJJIjoiIiwiZW1haWxWZXJpZmllZCI6ZmFsc2UsInBhc3N3b3JkVHJpZXMiOjAsIm9wdGVkSW5Gb3JFbWFpbCI6dHJ1ZSwiYWNjb3VudFN1c3BlbmRlZCI6ZmFsc2UsImFjY291bnRCbG9ja2VkIjpmYWxzZSwibWFya2VkRm9yRGVsZXRpb24iOmZhbHNlLCJkZWxldGVBY2NvdW50QWZ0ZXIiOiIwMDAxLTAxLTAxVDA1OjUzOjI4KzA1OjUzIiwiYWNjb3VudERlbGV0ZWQiOmZhbHNlLCJhY2NvdW50Q3JlYXRlZCI6dHJ1ZSwidG9rZW5zIjowLCJmaWxlcyI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyNS0xMS0wN1QxNTo1NzozMS43ODg4OTErMDU6MzAiLCJ1cGRhdGVkQXQiOiIyMDI1LTExLTA3VDE1OjU3OjMxLjgyODA3MiswNTozMCIsImlhdCI6MTc2MjUxMTI1NiwiZXhwIjoxNzYzMTE2MDU2fQ.J6OBccqec-oq0boxPECAZJhOZivtkH7Xc4uiHlpv-50
content-type: application/json

{
    "planName": "Buy Tokens",
    "planDescription": "This is a one-time purchase plan for tokens",
    "planPrice": 10,
    "planCurrency": "INR",
    "planDuration": 1,
    "planType": "one_time",
    "tokens": 1,
    "isActive": true,
    "features": [],
    "paymentGatewayId": {}
}

###
GET https://vital-logically-lemming.ngrok-free.app/products/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkpvaG4gRG9lIiwicm9sZSI6MiwiZW1haWwiOiJ0ZXN0MkBnbWFpbC5jb20iLCJwcm9maWxlUGljVVJJIjoiIiwiZW1haWxWZXJpZmllZCI6ZmFsc2UsInBhc3N3b3JkVHJpZXMiOjAsIm9wdGVkSW5Gb3JFbWFpbCI6dHJ1ZSwiYWNjb3VudFN1c3BlbmRlZCI6ZmFsc2UsImFjY291bnRCbG9ja2VkIjpmYWxzZSwibWFya2VkRm9yRGVsZXRpb24iOmZhbHNlLCJkZWxldGVBY2NvdW50QWZ0ZXIiOiIwMDAxLTAxLTAxVDA1OjUzOjI4KzA1OjUzIiwiYWNjb3VudERlbGV0ZWQiOmZhbHNlLCJhY2NvdW50Q3JlYXRlZCI6dHJ1ZSwidG9rZW5zIjowLCJmaWxlcyI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyNS0xMC0wNFQwMTozODoyOS44MDQwNDMrMDU6MzAiLCJ1cGRhdGVkQXQiOiIyMDI1LTEwLTIzVDE0OjQwOjUzLjExNjY3MiswNTozMCIsImlhdCI6MTc2MjUwOTE4OCwiZXhwIjoxNzYzMTEzOTg4fQ.s-5gSSt_lrPdY9phqG04U0EbbgkV-4HqATedPCSE5xI

###
GET https://vital-logically-lemming.ngrok-free.app/products/1/buy/razorpay?count=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkpvaG4gRG9lIiwicm9sZSI6MiwiZW1haWwiOiJ0ZXN0MkBnbWFpbC5jb20iLCJwcm9maWxlUGljVVJJIjoiIiwiZW1haWxWZXJpZmllZCI6ZmFsc2UsInBhc3N3b3JkVHJpZXMiOjAsIm9wdGVkSW5Gb3JFbWFpbCI6dHJ1ZSwiYWNjb3VudFN1c3BlbmRlZCI6ZmFsc2UsImFjY291bnRCbG9ja2VkIjpmYWxzZSwibWFya2VkRm9yRGVsZXRpb24iOmZhbHNlLCJkZWxldGVBY2NvdW50QWZ0ZXIiOiIwMDAxLTAxLTAxVDA1OjUzOjI4KzA1OjUzIiwiYWNjb3VudERlbGV0ZWQiOmZhbHNlLCJhY2NvdW50Q3JlYXRlZCI6dHJ1ZSwidG9rZW5zIjowLCJmaWxlcyI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyNS0xMS0wN1QxNTo1NzozMS43ODg4OTErMDU6MzAiLCJ1cGRhdGVkQXQiOiIyMDI1LTExLTA3VDE1OjU3OjMxLjgyODA3MiswNTozMCIsImlhdCI6MTc2MjUxMTI1NiwiZXhwIjoxNzYzMTE2MDU2fQ.J6OBccqec-oq0boxPECAZJhOZivtkH7Xc4uiHlpv-50
