POST http://localhost:8000/user/create
content-type: application/json

{
    "name": "John Doe",
    "email": "test2@gmail.com",
    "password": "abhay@123",
    "confirm_password": "abhay@123"
}

### Login
POST http://localhost:8000/user/login
content-type: application/json

{
  "email": "test2@gmail.com",
  "password": "abhay@123"
}

### Request Reset Password Link
GET http://localhost:8000/user/reset-password?email=abhay1029singh@gmail.com

### Reset Password
POST http://localhost:8000/user/reset-password
content-type: application/json

{
  "token": "hVKisM77QEs93uAlMAjglymlfEpkAblVWGTdJwdAfZn3bh9KOz5PaPPe",
  "password": "Abhay@9211",
  "email": "abhay1029singh@gmail.com"
}